version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  etl:
    build: .
    container_name: etl_pipeline
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
